### ISSUE TITLE
How to build the project ?

### ISSUE THREAD

**Issue by valeriobruno** [javaquery/zooviewer#9]
Hello,
I see you moved from Maven to Ant build script. How do I build the project ?
When i run ant

> BUILD FAILED
> C:\Users\valeriobruno\Work\zookeeper_viewers\zooviewer_java_query\nbproject\build-impl.xml:923: The following error occurred while executing this line:
> C:\Users\valeriobruno\Work\zookeeper_viewers\zooviewer_java_query\nbproject\build-impl.xml:263: Class not found: javac1.8

I am using java 8 compiler with JAVA_HOME defined and javac.exe in PATH.

_Valerio_

**Comment by javaquery** [comment]
Its NetBeans project.
